fragment BioParts on Bio {
  __typename
  subtitle
  headline
  bioParagraph1
  bioParagraph2
}

fragment EventsParts on Events {
  __typename
  category
  title
  description
}

fragment PublicationsParts on Publications {
  __typename
  type
  title
  description
  link
}
