//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  bio: Bio;
  bioConnection: BioConnection;
  events: Events;
  eventsConnection: EventsConnection;
  publications: Publications;
  publicationsConnection: PublicationsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBioArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBioConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BioFilter>;
};


export type QueryEventsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEventsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventsFilter>;
};


export type QueryPublicationsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPublicationsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PublicationsFilter>;
};

export type DocumentFilter = {
  bio?: InputMaybe<BioFilter>;
  events?: InputMaybe<EventsFilter>;
  publications?: InputMaybe<PublicationsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Bio | Events | Publications | Folder;

export type Bio = Node & Document & {
  __typename?: 'Bio';
  subtitle?: Maybe<Scalars['String']['output']>;
  headline?: Maybe<Scalars['String']['output']>;
  bioParagraph1?: Maybe<Scalars['String']['output']>;
  bioParagraph2?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BioFilter = {
  subtitle?: InputMaybe<StringFilter>;
  headline?: InputMaybe<StringFilter>;
  bioParagraph1?: InputMaybe<StringFilter>;
  bioParagraph2?: InputMaybe<StringFilter>;
};

export type BioConnectionEdges = {
  __typename?: 'BioConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Bio>;
};

export type BioConnection = Connection & {
  __typename?: 'BioConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BioConnectionEdges>>>;
};

export type Events = Node & Document & {
  __typename?: 'Events';
  category?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type EventsFilter = {
  category?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type EventsConnectionEdges = {
  __typename?: 'EventsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Events>;
};

export type EventsConnection = Connection & {
  __typename?: 'EventsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EventsConnectionEdges>>>;
};

export type Publications = Node & Document & {
  __typename?: 'Publications';
  type?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  link?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PublicationsFilter = {
  type?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  link?: InputMaybe<StringFilter>;
};

export type PublicationsConnectionEdges = {
  __typename?: 'PublicationsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Publications>;
};

export type PublicationsConnection = Connection & {
  __typename?: 'PublicationsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PublicationsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateBio: Bio;
  createBio: Bio;
  updateEvents: Events;
  createEvents: Events;
  updatePublications: Publications;
  createPublications: Publications;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateBioArgs = {
  relativePath: Scalars['String']['input'];
  params: BioMutation;
};


export type MutationCreateBioArgs = {
  relativePath: Scalars['String']['input'];
  params: BioMutation;
};


export type MutationUpdateEventsArgs = {
  relativePath: Scalars['String']['input'];
  params: EventsMutation;
};


export type MutationCreateEventsArgs = {
  relativePath: Scalars['String']['input'];
  params: EventsMutation;
};


export type MutationUpdatePublicationsArgs = {
  relativePath: Scalars['String']['input'];
  params: PublicationsMutation;
};


export type MutationCreatePublicationsArgs = {
  relativePath: Scalars['String']['input'];
  params: PublicationsMutation;
};

export type DocumentUpdateMutation = {
  bio?: InputMaybe<BioMutation>;
  events?: InputMaybe<EventsMutation>;
  publications?: InputMaybe<PublicationsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  bio?: InputMaybe<BioMutation>;
  events?: InputMaybe<EventsMutation>;
  publications?: InputMaybe<PublicationsMutation>;
};

export type BioMutation = {
  subtitle?: InputMaybe<Scalars['String']['input']>;
  headline?: InputMaybe<Scalars['String']['input']>;
  bioParagraph1?: InputMaybe<Scalars['String']['input']>;
  bioParagraph2?: InputMaybe<Scalars['String']['input']>;
};

export type EventsMutation = {
  category?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type PublicationsMutation = {
  type?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  link?: InputMaybe<Scalars['String']['input']>;
};

export type BioPartsFragment = { __typename: 'Bio', subtitle?: string | null, headline?: string | null, bioParagraph1?: string | null, bioParagraph2?: string | null };

export type EventsPartsFragment = { __typename: 'Events', category?: string | null, title?: string | null, description?: string | null };

export type PublicationsPartsFragment = { __typename: 'Publications', type?: string | null, title?: string | null, description?: string | null, link?: string | null };

export type BioQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BioQuery = { __typename?: 'Query', bio: { __typename: 'Bio', id: string, subtitle?: string | null, headline?: string | null, bioParagraph1?: string | null, bioParagraph2?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BioConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BioFilter>;
}>;


export type BioConnectionQuery = { __typename?: 'Query', bioConnection: { __typename?: 'BioConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BioConnectionEdges', cursor: string, node?: { __typename: 'Bio', id: string, subtitle?: string | null, headline?: string | null, bioParagraph1?: string | null, bioParagraph2?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type EventsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type EventsQuery = { __typename?: 'Query', events: { __typename: 'Events', id: string, category?: string | null, title?: string | null, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type EventsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventsFilter>;
}>;


export type EventsConnectionQuery = { __typename?: 'Query', eventsConnection: { __typename?: 'EventsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'EventsConnectionEdges', cursor: string, node?: { __typename: 'Events', id: string, category?: string | null, title?: string | null, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PublicationsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PublicationsQuery = { __typename?: 'Query', publications: { __typename: 'Publications', id: string, type?: string | null, title?: string | null, description?: string | null, link?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PublicationsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PublicationsFilter>;
}>;


export type PublicationsConnectionQuery = { __typename?: 'Query', publicationsConnection: { __typename?: 'PublicationsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PublicationsConnectionEdges', cursor: string, node?: { __typename: 'Publications', id: string, type?: string | null, title?: string | null, description?: string | null, link?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const BioPartsFragmentDoc = gql`
    fragment BioParts on Bio {
  __typename
  subtitle
  headline
  bioParagraph1
  bioParagraph2
}
    `;
export const EventsPartsFragmentDoc = gql`
    fragment EventsParts on Events {
  __typename
  category
  title
  description
}
    `;
export const PublicationsPartsFragmentDoc = gql`
    fragment PublicationsParts on Publications {
  __typename
  type
  title
  description
  link
}
    `;
export const BioDocument = gql`
    query bio($relativePath: String!) {
  bio(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BioParts
  }
}
    ${BioPartsFragmentDoc}`;
export const BioConnectionDocument = gql`
    query bioConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BioFilter) {
  bioConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BioParts
      }
    }
  }
}
    ${BioPartsFragmentDoc}`;
export const EventsDocument = gql`
    query events($relativePath: String!) {
  events(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EventsParts
  }
}
    ${EventsPartsFragmentDoc}`;
export const EventsConnectionDocument = gql`
    query eventsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EventsFilter) {
  eventsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EventsParts
      }
    }
  }
}
    ${EventsPartsFragmentDoc}`;
export const PublicationsDocument = gql`
    query publications($relativePath: String!) {
  publications(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PublicationsParts
  }
}
    ${PublicationsPartsFragmentDoc}`;
export const PublicationsConnectionDocument = gql`
    query publicationsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PublicationsFilter) {
  publicationsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PublicationsParts
      }
    }
  }
}
    ${PublicationsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      bio(variables: BioQueryVariables, options?: C): Promise<{data: BioQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BioQueryVariables, query: string}> {
        return requester<{data: BioQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BioQueryVariables, query: string}, BioQueryVariables>(BioDocument, variables, options);
      },
    bioConnection(variables?: BioConnectionQueryVariables, options?: C): Promise<{data: BioConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BioConnectionQueryVariables, query: string}> {
        return requester<{data: BioConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BioConnectionQueryVariables, query: string}, BioConnectionQueryVariables>(BioConnectionDocument, variables, options);
      },
    events(variables: EventsQueryVariables, options?: C): Promise<{data: EventsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsQueryVariables, query: string}> {
        return requester<{data: EventsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsQueryVariables, query: string}, EventsQueryVariables>(EventsDocument, variables, options);
      },
    eventsConnection(variables?: EventsConnectionQueryVariables, options?: C): Promise<{data: EventsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsConnectionQueryVariables, query: string}> {
        return requester<{data: EventsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsConnectionQueryVariables, query: string}, EventsConnectionQueryVariables>(EventsConnectionDocument, variables, options);
      },
    publications(variables: PublicationsQueryVariables, options?: C): Promise<{data: PublicationsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PublicationsQueryVariables, query: string}> {
        return requester<{data: PublicationsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PublicationsQueryVariables, query: string}, PublicationsQueryVariables>(PublicationsDocument, variables, options);
      },
    publicationsConnection(variables?: PublicationsConnectionQueryVariables, options?: C): Promise<{data: PublicationsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PublicationsConnectionQueryVariables, query: string}> {
        return requester<{data: PublicationsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PublicationsConnectionQueryVariables, query: string}, PublicationsConnectionQueryVariables>(PublicationsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/1.6/content/95de2861-b5ae-4ae0-953d-0a1e36e402d9/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  